config/routes.rb
CsvImport::Application.routes.draw do
  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :field1, :field2, :field3, :name

  def self.build_from_csv(row)
    custumer = Customer.new()
    custumer.name = row[0]
    custumer.field1 = row[1]
    custumer.field2 = row[2]
    custumer.field3 = row[3]
    custumer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    require 'csv'

    file = params[:customer][:file].read
    CSV.parse(file) do |row|
      @customer = Customer.build_from_csv(row)
      @customer.save!
    end

    #@customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= form_for @customer do |f|
  -if @customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      %ul
        - @customer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :field1
    = f.text_field :field1
  .field
    = f.label :field2
    = f.text_field :field2
  .field
    = f.label :field3
    = f.text_field :field3
  .actions
    = f.submit 'Save'

app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

app/views/customers/index.html.haml
%h1 Listing customers

%table
  %tr
    %th Name
    %th Field1
    %th Field2
    %th Field3
    %th
    %th
    %th

  - @customers.each do |customer|
    %tr
      %td= customer.name
      %td= customer.field1
      %td= customer.field2
      %td= customer.field3
      %td= link_to 'Show', customer
      %td= link_to 'Edit', edit_customer_path(customer)
      %td= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Customer', new_customer_path

app/views/customers/new.html.haml
%h1 New customer

= render 'form'

= link_to 'Back', customers_path

=form_for @customer, :html => {:multipart => true} do |f|
  .field
    =f.file_field :file
    =f.submit "upload"

app/views/customers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @customer.name
%p
  %b Field1:
  = @customer.field1
%p
  %b Field2:
  = @customer.field2
%p
  %b Field3:
  = @customer.field3

= link_to 'Edit', edit_customer_path(@customer)
\|
= link_to 'Back', customers_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvImport</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>